version: '3.9'

services:
  django:
    build: .
    container_name: django-container
    networks:
      - nginx_network
    restart: always

  nginx: 
    build: ./deployment/nginx
    ports:
      - 8085:80
    volumes_from:
      - django:rw
    container_name: nginx-container
    depends_on:
      - django
    networks:
      - nginx_network


  # db:
  #  image: mysql:5.7
  #  restart: always
  #  environment:
  #    MYSQL_DATABASE: 'cookbook'
  #    MYSQL_USER: 'admin'
  #    MYSQL_PASSWORD: 'admin'
  #    MYSQL_ROOT_PASSWORD: 'admin'
  #  ports:
  #    - '3306:3306'
  #  expose:
  #    - '3306'
  #  volumes:
  #    - my-db:/var/lib/mysql
  # Names our volume
 #volumes: 'cookbook-volume'
  #  my-db: 'cookbook'

networks: 
  nginx_network:
    driver: bridge

